blank_issues_enabled: false
contact_links:
  - name: Contacts
    email: Fabian.Zaenker@student.tu-freiberg.de
    email: Lucas-Valentin.Adler@student.tu-freiberg.de
    email: Simon.Hoertzsch@student.tu-freiberg.de
    about: If you have questions, reach out to us via email.
