# .github/workflows/liascript_pdf_export.yml

name: Generate and Commit LiaScript PDFs

on:
  push:
    branches:
      - documentation
    paths:
      # Trigger NUR bei Änderungen an .md Dateien im presentation Ordner (und Unterordnern)
      - 'presentation/**/*.md'

permissions:
  # 'actions: write' für upload-artifact (falls du es behalten willst)
  # 'contents: write' wird benötigt, um Commits zurück ins Repo zu pushen
  actions: write
  contents: write

jobs:
  build-and-commit-pdfs: # Job-Name angepasst
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Code auschecken (vom documentation Branch)
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: documentation
          # Wichtig: Token mit Schreibrechten auschecken für den späteren Push
          token: ${{ secrets.GITHUB_TOKEN }}

      # Schritt 2: Node.js einrichten
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Schritt 3: Google Chrome installieren
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Schritt 4: LiaScript Exporter installieren
      - name: Install LiaScript Exporter
        run: npm install -g @liascript/exporter

      # Schritt 5: PDFs für alle .md Dateien im presentation Ordner erstellen
      - name: Run LiaScript Exporter for all Markdown files
        run: |
          find presentation -name '*.md' | while read md_file; do
            base_name=$(basename "$md_file" .md)
            pdf_output="presentation/${base_name}.pdf"
            echo "Processing $md_file -> $pdf_output"
            liascript-exporter -f pdf -o "$pdf_output" -i "$md_file"
          done

      # --- NEUE SCHRITTE für Git Commit & Push ---

      # Schritt 6: Git konfigurieren
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Schritt 7: Änderungen hinzufügen und committen (nur wenn es Änderungen gibt)
      - name: Commit PDF changes
        run: |
          # Prüfen, ob sich PDF-Dateien geändert haben oder neu sind
          if ! git diff --quiet presentation/*.pdf; then
            echo "PDF changes detected. Committing..."
            git add presentation/*.pdf
            git commit -m "Automated PDF generation from LiaScript" -m "[ci skip]" # [ci skip] als zusätzliche Sicherheit gegen Loops
          else
            echo "No PDF changes to commit."
          fi

      # Schritt 8: Änderungen pushen
      - name: Push PDF changes
        run: |
          # Versuche einfach zu pushen. Git meldet, wenn nichts zu tun ist.
          # Der vorherige Schritt stellt sicher, dass nur gepusht wird, wenn ein Commit gemacht wurde
          # (wobei wir hier sehen, dass kein Commit gemacht wurde -> Push wird nichts tun)
          echo "Attempting to push changes if any were committed..."
          git push origin documentation

      # --- Ende der neuen Schritte ---

      # Schritt 9 (Optional): Generierte PDFs weiterhin als Artefakt hochladen
      # Kann nützlich sein für schnellen Zugriff oder als Backup
      - name: Upload PDF artifacts (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: waymo-presentation-pdfs
          path: presentation/*.pdf